package arc;

import arc.util.*;

/**
 * This interface encapsulates communication with the graphics processor. Depending on the available hardware and the current
 * {@link Application} configuration, access to {@link GL20} and {@link GL30} are provided here.
 * <p>
 * If supported by the backend, this interface lets you query the available display modes (graphics resolution and color depth)
 * and change it.
 * <p>
 * This interface can be used to switch between continuous and non-continuous rendering (see
 * {@link #setContinuousRendering(boolean)}), and to explicitly {@link #requestRendering()}.
 * <p>
 * There are many more utility classes that are not directly generated by the {@link Graphics} interfaces. See {@link VertexArray}
 * , {@link VertexBufferObject}, {@link IndexBufferObject}, {@link Mesh}, {@link Shader} and {@link FrameBuffer},
 * {@link Font}, {@link Batch} and so on. All these classes are managed, meaning they don't need to be reloaded on a context
 * loss. Explore the arc.graphics package for more classes that might come in handy.
 * @author mzechner
 *
 * @deprecated Just here for compatibility reasons, only contains methods about frame rate.
 *             Please use same methods from {@link Application} instead.
 */
@Deprecated
public abstract class Graphics implements Disposable{
    /**
     * Returns the id of the current frame. The general contract of this method is that the id is incremented only when the
     * application is in the running state right before calling the {@link ApplicationListener#update()} method. Also, the id of
     * the first frame is 0; the id of subsequent frames is guaranteed to take increasing values for 2<sup>63</sup>-1 rendering
     * cycles.
     * @return the id of the current frame
     *
     * @deprecated Use {@link Application#getFrameId()} instead.
     */
    @Deprecated
    public abstract long getFrameId();

    /**
     * @return the time span between the current frame and the last frame in seconds. Might be smoothed over n frames.
     *
     * @deprecated Use {@link Application#getDeltaTime()} instead.
     */
    @Deprecated
    public abstract float getDeltaTime();

    /**
     * @return the average number of frames per second
     *
     * @deprecated Use {@link Application#getFramesPerSecond()} instead.
     */
    @Deprecated
    public abstract int getFramesPerSecond();

    @Deprecated
    @Override
    public void dispose(){
    }
}
